Intervjusider - Statens vegvesen #237
varianter/variant.no pull request #244
Opened 2022-08-04 09:15 UTC by mortennordseth

Jeg har laget oppsett for intervjuer med varianter. Dette er laget likt som med jobbannonser (markdown filer). For øyeblikket blir intervjuene lagt bak /intervju, noe som trolig bør endres når prosjektsidene er på plass. 

Førsteutkast av intervjuet til Andreas kan sees på `/intervju/andreas-svv`

2022-08-04 10:33 UTC, hildeor requested changes
Ser bra ut 👍 
Eneste jeg ser er at skriftstørrelsene blir litt vel store på desktop 😅 
De bør være like som f. eks i den nye seksjonen "Bli en Variant".
Sånn at H1 = headingen "Bli en Variant" på forsiden, og ingressen = "For å kunne lage gode løsninger ........". Og brødteksten/hovedteksten blir lik størrelse som "Vi holder til i superfine lokaler i Trondheim, Oslo og Bergen. I tillegg har vi noen små, sjarme......."

Ble det forståelig forklart? 🙈 @mortennordseth

2022-08-04 11:16 UTC, hildeor approved these changes
Ser bra ut nå 💯

2022-08-04 11:16 UTC, hildeor commented
Får vi skråstilt den teksten her også? 😄 
<img width="330" alt="Skjermbilde 2022-08-04 kl  13 16 15" src="https://user-images.githubusercontent.com/8980523/182834167-8c41e491-ba3e-4185-92eb-940500255404.png">

2022-08-04 11:18 UTC, mikaelbr commented
Dette blir bra! 🚀

2022-08-05 06:56 UTC, cbrevik requested changes
Ser bra ut dette! Noen få forslag til forbedring. Men tror jevnt over ser det ganske ferdig ut 🏎️

2022-08-05 06:56 UTC, cbrevik commented on src/interviews/utils/interviewHandlers.ts
> +  location: string;
I fra Figma ser det ut til at det kan være flere lokasjoner, så denne burde kanskje være en `string[]`?

2022-08-05 06:56 UTC, cbrevik commented on src/interviews/utils/interviewHandlers.ts
> +  duration: string;
Lurer på om duration bør være en `durationFrom` og `durationTill`. Og i det tilfellet `durationTill` ikke er satt så kommer pila `->` (for å presisere at det er pågående)?

2022-08-05 06:56 UTC, cbrevik commented on src/interviews/index.tsx
> +        '</div>';
Kanskje refaktorere denne ut til en egen funksjon som tar inn `interview`?

2022-08-05 06:56 UTC, cbrevik commented on src/interviews/utils/interviewHandlers.ts
> +  location: string;
Og så rendrer den ut flere i det tilfellet, med hver sin unike farge

2022-08-05 06:56 UTC, cbrevik commented on pages/intervju/[interview].tsx
> +  interview.image = variant[0]?.imageUrl || '/interviews/placeholder_blob.png';
På sikt burde vi kanskje heller ha egne bilder som defineres i interview-markdownen. Kanskje vi skulle sjekket om `image` finnes på `interview`, og hvis ikke bruke CV-bilde, og hvis ikke bruke placeholder?

2022-08-15 07:27 UTC, mortennordseth commented
> Ser bra ut dette! Noen få forslag til forbedring. Men tror jevnt over ser det ganske ferdig ut 🏎️

Da har jeg sett på forslagene til endring og endret deretter, @cbrevik  🥳

2022-08-15 08:13 UTC, cbrevik approved these changes
Awesome 🚀 Dette ser veldig bra ut, kjør på tenker jeg!

2022-08-15 09:13 UTC, merged