øker responsiviteten til siden
varianter/variant.no pull request #385
Opened 2023-07-06 09:07 UTC by haakoaho

2023-07-07 09:10 UTC, teatimes requested changes

2023-07-07 09:12 UTC, teatimes commented
Mye bedre rendring av "Hva går sommerjobben ut på?" Ser det fortsatt er noe rar rendring på andre deler av siden:

![Screenshot from 2023-07-07 10-59-58](https://github.com/varianter/variant.no/assets/10518767/3843b748-8ffc-4f20-a713-85d32e1b4514)

![Screenshot from 2023-07-07 11-01-35](https://github.com/varianter/variant.no/assets/10518767/78e7ecc5-f162-4993-b97b-c3fd4d93d485)
 
![Screenshot from 2023-07-07 11-04-18](https://github.com/varianter/variant.no/assets/10518767/427995f4-f7ad-4791-9437-488132911ed1)

![Screenshot from 2023-07-07 11-04-30](https://github.com/varianter/variant.no/assets/10518767/596a567f-1305-46bf-a69a-661aef5f2d91)

![Screenshot from 2023-07-07 11-07-08](https://github.com/varianter/variant.no/assets/10518767/11f51978-1695-4c14-a814-41dabf14294e)

2023-07-07 11:54 UTC, teatimes commented
Jeg finner fortsatt en del av de samme feilene (i firefox)

Her blir det litt overlapp på teksten, og jeg ville utnyttet bredden bedre slik at det ikke blir så mye tomrom på høyresiden
![Screenshot from 2023-07-07 13-39-51](https://github.com/varianter/variant.no/assets/10518767/ad4f3117-9ce0-4215-b0df-7f7f118231ca)

Her kommer det et bilde for mye når bredden er 1400px
![Screenshot from 2023-07-07 13-21-19](https://github.com/varianter/variant.no/assets/10518767/3d2d2b47-b6e3-4db3-8b43-193867845c96)

Her ville jeg utnytet bredden bedre. Blir også overlapp på bildet på smal skjerm
![Screenshot from 2023-07-07 13-40-07](https://github.com/varianter/variant.no/assets/10518767/64b9bdbc-c2c8-4b87-ae9b-d19583d59730)
![Screenshot from 2023-07-07 13-40-32](https://github.com/varianter/variant.no/assets/10518767/8c117a5c-f988-43ef-807b-f6a349e5ede3)

Her føler jeg også det blir mye tomt på høyresida, samt at "Trykk her for å lese mer om temaet" forsvinner på flere ulike bredder (men vises innimellom)
![Screenshot from 2023-07-07 13-41-53](https://github.com/varianter/variant.no/assets/10518767/4c5a9f3d-7983-46e4-92c7-b849b7980cc4)

Her blir det overlapp på bilde og tekst, samt at bildet på liten skjerm havner nederst
![image](https://github.com/varianter/variant.no/assets/10518767/b3cdda15-c108-4a73-85c2-d286deea1ad9)

Er det ikke rart at bildet av en av personene er så mye større enn de andre?
![image](https://github.com/varianter/variant.no/assets/10518767/802d24e3-1dcf-42be-99a2-0358ba5015b5)

Samme her ang mye tom plass på høyresiden
![Screenshot from 2023-07-07 13-47-45](https://github.com/varianter/variant.no/assets/10518767/e2be8546-e332-48fe-9641-8d0b13d85d54)

Deler av bildet forsvinner ut av skjermen på ca 1108 px
![Screenshot from 2023-07-07 13-48-21](https://github.com/varianter/variant.no/assets/10518767/722735e8-0588-419a-8f15-6d8eb9351f21)

2023-08-02 18:06 UTC, mikaelbr commented
Antar denne lukkes nå pga #388 . åpne igjen ved behov

2023-08-02 18:06 UTC, closed without merging